// ============================================================
// Portfolio data — projects, experience, taxonomy.
// Edit this one file to add/change projects. Everything else
// (layout, grouping, modal) renders from here.
// ============================================================

window.PROFILE = {
  name: "Johannes Dommnich",
  initials: "JD",
  kicker: "Hi, I'm Johannes",
  email: "jdommnich@gmail.com",
  location: "London, UK",
  photo: "images/johannes-profile.jpg",
  links: {
    linkedin: "https://www.linkedin.com/in/johannesdommnich/",
    github: "https://github.com/Jodedo3000",
  },
};

// Use-case taxonomy (the visible category). Order = display order.
// Muted Scandinavian palette — soft, desaturated tones used as gentle tile
// tints + section dots. (The blue brand colour for buttons/nav is separate.)
window.USE_CASES = {
  productivity:         { label: "Productivity",       accent: "#6d8aa8" }, // dusty blue
  "product-management": { label: "Product Management", accent: "#8f86a6" }, // muted heather
  "job-search":         { label: "Job Search",         accent: "#c08a5e" }, // soft terracotta
  "mental-wellbeing":   { label: "Mental Wellbeing",   accent: "#7e9b80" }, // sage green
  "fun-games":          { label: "Fun & Games",        accent: "#c6a96b" }, // soft ochre
  "japanese-study":     { label: "Japanese Study",     accent: "#5f9990" }, // muted teal
  ecommerce:            { label: "E-Commerce",         accent: "#a8766a" }, // muted brick
};

// Build-tool taxonomy — the primary tool each project was built with.
// `color` drives the dots in the Technology grouping + chips.
window.TECH = {
  replit:      { label: "Replit",       color: "#F26207", build: true },
  bolt:        { label: "Bolt",         color: "#3178C6", build: true },
  firebase:    { label: "Firebase / Web", color: "#4F46E5", build: true },
  claude_code: { label: "Claude Code",  color: "#D97757", build: true },
  custom_gpt:  { label: "Custom GPT",   color: "#10A37F", build: true },
  n8n:         { label: "n8n",          color: "#EA4B71", build: true },
  voice_ai:    { label: "Voice AI",     color: "#7A5AE0", build: true },
  native:      { label: "Native App",   color: "#374151", build: true },
};

// Order of build-tool sections (most-used first).
window.BUILD_TOOLS = ["replit", "bolt", "firebase", "claude_code", "custom_gpt", "n8n", "voice_ai", "native"];

window.PROJECTS = [
  {
    id: "0job1",
    title: "0job1",
    tagline: "Value-first job applications",
    useCase: "job-search",
    buildTool: "firebase",
    featured: true,
    status: "Live",
    image: "images/0job1-app.png",
    stack: ["React", "Firebase", "Gemini", "Anthropic", "Perplexity", "Stripe", "TypeScript"],
    role: "Solo build — product, design & engineering",
    outcome: "Faster, higher-quality applications with concrete artifacts recruiters can review.",
    short:
      "Turns a job application into a full, value-first package, not just a CV. Automated company research produces a briefing memo, fit score, tailored CV and cover letter, video-pitch support, and an outreach message.",
    long:
      "0job1.com turns a job application into a full, value-first package, not just a CV. It automates company research and generates a briefing memo, fit score, future-focused case-study ideas, a tailored CV and cover letter, video-pitch support, and an outreach message. The core outcome is faster, higher-quality, more differentiated applications with concrete artifacts a recruiter can actually review. Key learnings: reliability beats one big model call — splitting outputs into smaller calls prevents malformed responses; prompt scope matters, so sending only essential context improves quality and cuts latency; the UX has to reflect async reality with clear loading states; deterministic post-processing is essential for fit scoring; and users need a manual override to stay in control.",
    links: { live: "https://0job1.com" },
  },
  {
    id: "shuheit",
    title: "Shuheit",
    tagline: "Habit tracker for iPhone",
    useCase: "productivity",
    buildTool: "native",
    featured: true,
    status: "Live",
    image: "images/shuheit-habit-tracker.png",
    stack: ["iOS", "Swift", "AI"],
    role: "Solo build — design & engineering",
    short: "Track daily habits with intelligent insights and clean progress visualization.",
    long: "A native iOS application for tracking daily habits, with intelligent insights and progress visualization that keeps the daily loop simple and motivating.",
    links: { live: "https://apps.apple.com/us/app/shuheit/id6751883878", liveLabel: "Visit Product" },
  },
  {
    id: "newsletter-summarizer",
    title: "AI Newsletter Summarizer",
    tagline: "Your inbox, distilled daily",
    useCase: "productivity",
    buildTool: "replit",
    status: "Private",
    image: "images/newsletter-summarizer.png",
    stack: ["Replit", "Gmail", "AI", "Automation"],
    role: "Solo build — automation",
    short: "A Replit automation that scans Gmail for the last 24 hours, summarises every newsletter, and emails you a single digest.",
    long: "Built with Replit Agents and Automations using the Gmail connector. It checks the Gmail inbox for the last 24 hours, summarises all newsletters, and sends one digest email. Not publicly available.",
    links: {},
  },
  {
    id: "decision-compass",
    title: "Decision Compass GPT",
    tagline: "A calm guide for big decisions",
    useCase: "productivity",
    buildTool: "custom_gpt",
    status: "Live",
    image: "images/decision-compass.png",
    stack: ["GPT", "Decision Making", "AI"],
    role: "Solo build — prompt design",
    short: "A calm, structured GPT for thoughtful life, career, and strategic decisions, built on the WRAP framework and Shane Parrish's mental models.",
    long: "Decision Compass GPT is a calm, structured guide designed to help you make thoughtful life, career, and strategic decisions. It draws on the WRAP framework from Decisive by Chip and Dan Heath, the mental-model and blind-spot tools from Clear Thinking by Shane Parrish, and principles of values-aligned, intentional decision-making.",
    links: { live: "https://chatgpt.com/g/g-691602a6db50819192c56667497de0d4-decision-compass-gpt" },
  },
  {
    id: "snipnook",
    title: "Snipnook",
    tagline: "Smart bookmark manager",
    useCase: "productivity",
    buildTool: "replit",
    status: "Live",
    image: "images/snipnook-bookmarks.png",
    stack: ["Chrome Extension", "Replit"],
    role: "Solo build — design & engineering",
    short: "A Chrome extension for saving URLs, highlighting text, and capturing images from any page. A Readwise-like experience for the whole web.",
    long: "A Chrome extension for saving bookmarks and highlights instantly. Snipnook lets you save URLs, highlight text snippets, and capture images from any webpage. Built as part of a Replit community training, it gives you a Readwise-like experience for the whole web.",
    links: { live: "https://chromewebstore.google.com/detail/snipnook-bookmark-manager/alfphgaboipomehlbkhcmimhlhjebmff?utm_source=item-share-cb" },
  },
  {
    id: "pomodoro",
    title: "Pomodoro Timer",
    tagline: "A focused desktop timer",
    useCase: "productivity",
    buildTool: "native",
    status: "Private",
    image: "images/pomodoro-timer.png",
    stack: ["macOS", "Desktop App"],
    role: "Solo build — design & engineering",
    short: "A simple, native Pomodoro timer that lives on the Mac desktop.",
    long: "A simple Pomodoro timer for the Mac desktop, with native app functionality. Not publicly available.",
    links: {},
  },
  {
    id: "pm-hub",
    title: "Product Management Hub",
    tagline: "99+ pages of PM mastery",
    useCase: "product-management",
    buildTool: "firebase",
    featured: true,
    status: "Live",
    image: "images/pm-knowledge-hub.png",
    stack: ["Learning Platform", "PM", "AI"],
    role: "Solo build — product, design & engineering",
    short: "A learning platform for product managers: 99+ curated pages across strategy, psychology, metrics, decision-making, and AI for PMs.",
    long: "PM Knowledge Hub is a comprehensive learning platform for product managers, featuring 99+ curated pages across strategy, psychology, metrics, decision-making, and AI for PMs. Each topic page combines articles, videos, podcasts, books, AI-generated audio debates, visual infographics, and interactive flashcards.",
    links: { live: "https://pmknowledgehubv2.web.app/product-mastery", liveLabel: "Visit Product" },
  },
  {
    id: "claude-skills-pm",
    title: "Claude Skills for PMs",
    tagline: "Specialist briefings for Claude Code",
    useCase: "product-management",
    buildTool: "claude_code",
    featured: true,
    status: "Live",
    image: "images/claude-skills-pm.png",
    stack: ["Claude Code", "AI", "Prompt Engineering", "PM Tooling"],
    role: "Solo build — design & prompt engineering",
    outcome: "The first skill, AI Evals, hit a 100% pass rate on completeness vs. 67% without it.",
    short: "A suite of SKILL.md files that give PMs consistent, expert-level AI outputs from Claude Code without writing exhaustive prompts every time.",
    long: "A suite of structured SKILL.md files for Claude Code that give PMs consistent, high-quality AI outputs without writing exhaustive prompts every time. Each skill acts as a specialist briefing, defining the process, structure, and quality bar so Claude delivers complete, expert-level deliverables. The first skill, AI Evals, achieved a 100% pass rate on completeness criteria vs. 67% without it. More are in development: PRD writing, user-interview scripts, feature prioritisation, competitive teardowns, and retrospective facilitation.",
    links: { github: "https://github.com/Jodedo3000/ClaudeSkillsPM" },
  },
  {
    id: "0job1-crm",
    title: "AppTrack",
    tagline: "A CRM for your job hunt",
    useCase: "job-search",
    buildTool: "replit",
    status: "Sunset",
    image: "images/apptrack-crm.png",
    stack: ["CRM", "Replit", "Full-Stack"],
    role: "Solo build — product, design & engineering",
    short: "A custom CRM for tracking job applications: status flows, notes, job metadata, timeline visualization, and import/export. Now sunset.",
    long: "A custom CRM system for tracking job applications, with key stats, status flows, notes, job metadata, timeline visualization, and data import/export. This project has been sunset.",
    links: {},
  },
  {
    id: "product-sense",
    title: "Product Sense Interview Canvas",
    tagline: "Structure for PM interviews",
    useCase: "job-search",
    buildTool: "bolt",
    status: "Live",
    image: "images/product-sense-canvas.png",
    stack: ["Interview Prep", "Canvas", "PM"],
    role: "Solo build — design & engineering",
    short: "A timed canvas that structures product-sense interviews: section timers, a mockup space, and a journey-to-psych-graph map for spotting pain points and delighters.",
    long: "Product Sense interviews are common in the PM interview process. This tool provides a structure to guide thinking and prioritization. It includes timers per section, a canvas for mockups, and a mapping of user-journey steps to a psych-graph to identify pain points and delighters.",
    links: { live: "https://snazzy-dragon-1a0e28.netlify.app/" },
  },
  {
    id: "behavioral-gpt",
    title: "Behavioural Interview GPT",
    tagline: "STAR stories on demand",
    useCase: "job-search",
    buildTool: "custom_gpt",
    status: "Live",
    image: "images/behavioral-interview-gpt.png",
    stack: ["GPT", "STAR Framework", "Interview"],
    role: "Solo build — prompt design",
    short: "A GPT that helps you write STAR-framework stories to answer behavioural interview questions.",
    long: "A custom GPT that helps you write stories using the STAR framework to answer behavioural job-interview questions.",
    links: { live: "https://chatgpt.com/g/g-6849a4bb237c81919253adb88f2550cf-answers-for-behavioural-interview-questions" },
  },
  {
    id: "cv-customizer",
    title: "CV Customizer",
    tagline: "Role-specific CVs and cover letters",
    useCase: "job-search",
    buildTool: "claude_code",
    status: "Live",
    image: "images/cv-customizer.png",
    stack: ["Claude", "Google Cloud", "AI"],
    role: "Solo build — design & engineering",
    short: "Feed it a job description and my full CV; it returns a focused, role-specific CV and a matching cover letter that surface the experience that genuinely fits.",
    long: "A CV-tailoring assistant that takes any job description and my full CV, then produces a focused, role-specific CV and a matching cover letter. It highlights the parts of my experience that genuinely match the role. Runs on Claude Code and a Claude API client, deployed in Google Cloud.",
    links: { live: "https://cvtailor-328667633168.us-central1.run.app/" },
  },
  {
    id: "act-chatbot",
    title: "ACT Chatbot with RAG",
    tagline: "Source-grounded answers from your PDFs",
    useCase: "mental-wellbeing",
    buildTool: "n8n",
    status: "Live",
    image: "images/act-chatbot-rag.png",
    stack: ["RAG", "n8n", "Pinecone", "GPT-4", "Lovable"],
    role: "Solo build — workflow & engineering",
    short: "An end-to-end RAG chatbot that answers questions over a set of PDFs with accurate, source-grounded responses.",
    long: "An end-to-end RAG chatbot that lets users query a set of PDFs with accurate, source-grounded answers. It uses n8n for workflow automation, Pinecone for vector search, GPT-4.0-mini for cost-efficient reasoning, and a Lovable front end.",
    links: { live: "https://robottoka-talker.lovable.app/" },
  },
  {
    id: "calmeno",
    title: "Calmeno",
    tagline: "Guided deep breathing",
    useCase: "mental-wellbeing",
    buildTool: "bolt",
    status: "Private",
    image: "images/calmeno-breathing.jpeg",
    stack: ["Wellness", "Mobile"],
    role: "Solo build — design & engineering",
    short: "A self-guided deep-breathing app with personalized exercises and mindfulness features.",
    long: "A self-guided deep-breathing application with personalized breathing exercises and mindfulness features. Not publicly available.",
    links: {},
  },
  {
    id: "mindfulness-coach",
    title: "Mindfulness Coach",
    tagline: "Five minutes can change your day",
    useCase: "mental-wellbeing",
    buildTool: "voice_ai",
    featured: true,
    status: "Live",
    image: "images/mindfulness-coach.png",
    stack: ["ElevenLabs", "Voice AI", "Wellness"],
    role: "Solo build — design & engineering",
    short: "A calm space for short check-ins, guided breathing, and reflection, led by a custom ElevenLabs voice agent.",
    long: "A calm, focused space for short check-ins, guided breathing, and gentle reflection, built around a single idea: five minutes can change your day. The coach uses an ElevenLabs voice agent with a custom-defined voice.",
    links: { live: "https://cerulean-sunshine-3126f0.netlify.app/" },
  },
  {
    id: "ai-mental-health-repo",
    title: "AI × Mental Health Knowledge Repository",
    tagline: "Mapping where AI meets mental health",
    useCase: "mental-wellbeing",
    buildTool: "claude_code",
    status: "Live",
    image: "images/ai-mental-health-repo.png",
    stack: ["Claude Code", "Next.js", "Supabase"],
    role: "Solo build — design & engineering",
    short: "A searchable, filterable wiki tracking the apps, research, and organizations working at the intersection of AI and mental health.",
    long: "A searchable knowledge repository mapping where AI meets mental health and wellbeing. It works as both a professional resource for industry analysis and a personal growth tool. Entries cover apps, research, and organizations, with fuzzy search and filtering across resource type, clinical vs. wellness focus, conditions, and therapeutic framework (CBT, ACT, positive psychology, mindfulness). Evidence is graded from RCT down to peer-reviewed and pilot studies. Built with Claude Code.",
    links: { live: "https://benevolent-conkies-248719.netlify.app/" },
  },
  {
    id: "sakura-sensei",
    title: "Sakura Sensei",
    tagline: "Voice-first Japanese tutor",
    useCase: "japanese-study",
    buildTool: "voice_ai",
    featured: true,
    status: "Live",
    image: "images/sakura-sensei.png",
    stack: ["Voice AI", "Japanese", "Google Cloud", "Conversation"],
    role: "Solo build — design & engineering",
    short: "Pick a topic and practice speaking Japanese out loud with an animated sensei. No typing, no drills — just speak and get instant feedback.",
    long: "A voice-first Japanese conversation tutor powered by AI. Pick a topic — your day, hobbies, food, weekend plans — and practice speaking Japanese out loud with an animated sensei character. It is designed to reduce the friction of real conversation practice: no typing, no text-heavy drills, just speak and get instant feedback. Built on Google Cloud Run with a voice interface.",
    links: { live: "https://sakura-sensei-japanese-voice-tutor-169208607964.us-west1.run.app/" },
  },
  {
    id: "japanese-vocab",
    title: "Japanese Vocabulary Trainer",
    tagline: "Spaced-repetition flashcards",
    useCase: "japanese-study",
    buildTool: "bolt",
    status: "Live",
    image: "images/japanese-vocab-trainer.png",
    stack: ["Japanese", "Education", "Flashcards"],
    role: "Solo build — design & engineering",
    short: "A flashcard vocabulary trainer with spaced repetition, audio pronunciation, example sentences, and JLPT level tagging.",
    long: "A flashcard-based vocabulary trainer for learning Japanese. It features spaced repetition, audio pronunciation, example sentences, and JLPT level tagging, covering kanji, hiragana readings, and English translations with a clean study interface.",
    links: { live: "https://japanese-vocab-flash-3912.bolt.host/" },
  },
  {
    id: "tokyo-flashcards",
    title: "Tokyo Subway Kanji Flashcards",
    tagline: "Read every Tokyo Metro station",
    useCase: "japanese-study",
    buildTool: "bolt",
    status: "Private",
    image: "images/tokyo-subway-flashcards.png",
    stack: ["Japanese", "Education", "Flashcards"],
    role: "Solo build — design & engineering",
    short: "Flashcards for memorising every Tokyo Metro station and line name in kanji.",
    long: "A flashcards memorization app for all Tokyo Metro stations and line names in their kanji writing. Not publicly available.",
    links: {},
  },
  {
    id: "japan-blog",
    title: "Japan Travel Blog",
    tagline: "A journey, documented",
    useCase: "fun-games",
    buildTool: "firebase",
    status: "Live",
    image: "images/japan-travel-blog.png",
    stack: ["Travel", "Blog", "Photography"],
    role: "Solo build — design & engineering",
    short: "A personal travel blog documenting a recent trip to Japan with photo galleries, stories, and reflections.",
    long: "A personal travel blog documenting a recent journey to Japan, with photo galleries, stories, and reflections.",
    links: { live: "https://traveljournal-b437d.web.app/#two-days-before-departure" },
  },
  {
    id: "neon-pong",
    title: "Neon Pong",
    tagline: "Retro arcade, neon glow",
    useCase: "fun-games",
    buildTool: "replit",
    status: "Live",
    image: "images/neon-pong.png",
    stack: ["Game", "Replit", "Arcade"],
    role: "Solo build — game design & engineering",
    short: "A retro arcade Pong revival with neon aesthetics and pixel-perfect gameplay, built as a one-shot prompt project.",
    long: "A retro arcade-style Pong game with neon aesthetics and pixel-perfect gameplay. This classic arcade revival was a fun one-shot prompt project built with Replit.",
    links: { live: "https://retro-pong--johannesdommnic.replit.app/" },
  },
  {
    id: "fluffy-chess",
    title: "Fluffy Chess",
    tagline: "Chess, with fluffy pieces",
    useCase: "fun-games",
    buildTool: "replit",
    status: "Live",
    image: "images/fluffy-chess.png",
    stack: ["Game", "Replit", "Chess"],
    role: "Solo build — for my daughter",
    short: "A custom chess game built for my 8-year-old daughter, with adorable fluffy characters as pieces on a soft pastel board.",
    long: "A custom chess game designed for my 8-year-old daughter, who loves chess. Combining her passion for chess with her love of fluffy toys, this version features adorable fluffy characters as the pieces, set on a soft pastel board.",
    links: { live: "https://fluffy-chess--johannesdommnic.replit.app/" },
  },
  {
    id: "voice-cloning",
    title: "Voice Cloning from YouTube",
    tagline: "Bulk voice profiles, automated",
    useCase: "fun-games",
    buildTool: "n8n",
    status: "Private",
    image: "images/voice-cloning-youtube.png",
    stack: ["n8n", "ElevenLabs", "Automation"],
    role: "Solo build — workflow automation",
    short: "An n8n workflow that extracts audio from YouTube videos and creates AI voice profiles in ElevenLabs, batched via Google Sheets.",
    long: "An n8n workflow automation that performs bulk voice cloning by extracting audio from YouTube videos and creating AI voice profiles in ElevenLabs. It integrates with Google Sheets for batch processing. Not publicly available.",
    links: {},
  },
  {
    id: "tokyo-stories",
    title: "Tokyo Story Generator",
    tagline: "Explore Tokyo through fiction",
    useCase: "fun-games",
    buildTool: "bolt",
    status: "Private",
    image: "images/tokyo-story-generator.jpg",
    stack: ["AI", "Stories", "Tokyo"],
    role: "Solo build — design & engineering",
    short: "AI-generated interactive stories that explore Tokyo through the styles of different authors, linked to real locations, cafes, and restaurants.",
    long: "Explore Tokyo through AI-generated interactive stories, with links to real locations, restaurants, and cafes, written in the style of various authors. Not publicly available.",
    links: {},
  },
  {
    id: "yuki-shop",
    title: "Japanese Patisserie Shop",
    tagline: "Pastry ordering, sorted",
    useCase: "ecommerce",
    buildTool: "claude_code",
    status: "Live",
    image: "images/yuki-patisserie-shop.png",
    stack: ["Claude Code", "E-Commerce", "Full-Stack"],
    role: "Built for my wife's pastry business",
    short: "An online shop for my wife's Japanese patisserie, selling pastries to London's Japanese community. Built to replace the chaos of WhatsApp and email ordering after a Mont Blanc mix-up.",
    long: "My wife is a Japanese patissier who sells her pastries to the Japanese community in London. Orders used to come in over WhatsApp and email, which got messy fast — the final straw was a Mont Blanc order mix-up. I built her a proper online shop so customers can browse, order, and pay without the back-and-forth. Built with Claude Code.",
    links: { live: "https://yukishop-production.up.railway.app/" },
  },
];

window.EXPERIENCE = [
  {
    org: "Microsoft AI",
    role: "Principal Product Manager",
    period: "Aug 2019 — Sep 2025",
    bullets: [
      "Increased CTR by 10% and DAU by 5% by proposing and delivering a scalable AI-driven content pipeline, supported by a structured evaluation framework to maintain editorial quality.",
      "Improved partner satisfaction by 2.5x by transforming a critical internal CRM and operations platform, boosting reliability to 99.9% uptime and cutting support issues by 50%.",
      "Reduced reporting timelines by 67% by delivering a rev-share automation system that unified fragmented ad data.",
      "Led a complex subscription pilot for top-tier publishers; when results fell short, pivoted to launch a high-performing lead-gen module that scaled globally.",
      "Scaled a tipping feature to 170+ publishers and creators; led UX improvements that drove a 45x increase in free tips and 10x growth in points-based tips.",
      "Led a high-priority initiative to bring local journalism, creator content, and new monetization to MSN, launching tipping and subscriptions in 5 months by aligning 10+ teams.",
    ],
  },
  {
    org: "Microsoft",
    role: "Senior Product Manager, Business Operations",
    period: "Nov 2015 — Aug 2019",
    bullets: [
      "Built a centralized initiative-planning system from 0 to 1 and led the end-to-end planning process across MSN regions, enabling cross-regional alignment and leadership visibility into 100+ initiatives.",
      "Brought clarity to a derailed advertising-revenue data project, fixing foundational quality issues and launching a trusted monetization source that combined revenue data from dozens of global advertising partners.",
    ],
  },
  {
    org: "Microsoft",
    role: "Senior Lead Product Manager",
    period: "Feb 2013 — Nov 2015",
    bullets: [
      "Led international recovery post-MSN relaunch across 50+ markets and 28 languages, driving a 25% YoY engagement uplift and similar gains in volume and revenue within 6 months.",
      "Scaled and refocused an international team of 10 PMs across six countries, driving product relevance through market insights, stakeholder alignment, and strategic partnerships.",
    ],
  },
  {
    org: "Microsoft",
    role: "Senior Product Manager",
    period: "Oct 2008 — Jan 2013",
    bullets: [
      "Led complex, high-impact initiatives across MSN International, delivering a next-gen CMS relaunch, migrating global content feeds, and launching a new mobile web experience.",
      "Integrated MSN into Windows 8 apps while mentoring junior PMs, fostering a KPI-focused culture, and running market experiments through an innovation pipeline.",
    ],
  },
  {
    org: "Yahoo!",
    role: "Product Manager, Mobile",
    period: "2006 — 2008",
    bullets: [
      "Led mobile product initiatives in a rapidly evolving mobile landscape.",
      "Developed and launched mobile web experiences and applications.",
    ],
  },
  {
    org: "Jamba! / Jamster",
    role: "Key Account Manager",
    period: "2005 — 2006",
    bullets: [
      "Managed key partnerships and client relationships in the mobile entertainment space.",
      "Drove revenue growth through strategic account management.",
    ],
  },
  {
    org: "Reflact AG",
    role: "Project Manager",
    period: "2004 — 2005",
    bullets: [
      "Managed cross-functional projects and client deliverables.",
      "Coordinated teams to deliver successful project outcomes.",
    ],
  },
  {
    org: "Hermes Credit Insurance",
    role: "Project Manager",
    period: "2003 — 2004",
    bullets: [
      "Led project initiatives in the financial-services sector.",
      "Managed stakeholder relationships and project delivery.",
    ],
  },
  {
    org: "Sinner Schrader",
    role: "Frontend Producer",
    period: "2002 — 2003",
    bullets: [
      "Produced frontend experiences for digital projects.",
      "Coordinated with design and development teams to deliver high-quality web solutions.",
    ],
  },
];

window.EDUCATION = {
  school: "University of Koblenz and Landau",
  degree: "Master's degree in Psychology",
  period: "Grade: Excellent (Sehr gut)",
};
